export const ROUTES = {
  HOME: '/home',
  ANALYZE_ADDRESS: '/analyze-address',
  ANALYZE_SMART_CONTRACT: '/analyze-smart-contract',
  ANALYZE_ADDRESS_RESULT: '/analyze-address-result',
  ANALYZE_SMART_CONTRACT_RESULT: '/analyze-smart-contract-result',
  ANALYZE_SMART_CONTRACT_PROGRESS: '/analyze-smart-contract-progress',
  HISTORY: '/history',
  SCAN_HISTORY: '/scan-history',
  DETAIL_HISTORY: '/history/:id',
  ACCOUNT: '/account',
  ANALYZE_PROGRESS: '/analyze-progress',
  FAILED: '/failed',
  ANALYZE_ADDRESS_COMMUNITY_RESULT: '/analyze-address-community-result',
  WELCOME: '/',
  AI_ANALYZER: '/ai-analyzer',
  SETTING: '/setting',
  ALL_NETWORK: '/all-network',
  CREATE_WALLET: '/create-wallet',
  WALLET_HOME: '/wallet-home',
  MANAGE_NETWORK: '/manage-network',
  RECEIVE: '/receive',
  SEND: '/send',
}