export const ROUTES = {
  HOME: '/home',
  ANALYZE_ADDRESS: '/analyze-address',
  ANALYZE_SMART_CONTRACT: '/analyze-smart-contract',
  ANALYZE_ADDRESS_RESULT: '/analyze-address-result',
  ANALYZE_SMART_CONTRACT_RESULT: '/analyze-smart-contract-result',
  ANALYZE_SMART_CONTRACT_PROGRESS: '/analyze-smart-contract-progress',
  HISTORY: '/history',
  DETAIL_HISTORY: '/history/:id',
  ACCOUNT: '/account',
  ANALYZE_PROGRESS: '/analyze-progress',
  FAILED: '/failed',
  ANALYZE_ADDRESS_COMMUNITY_RESULT: '/analyze-address-community-result',
  WELCOME: '/',
}