export const ROUTES = {
  HOME: '/home',
  ANALYZE_ADDRESS: '/analyze-address',
  ANALYZE_SMART_CONTRACT: '/analyze-smart-contract',
  ANALYZE_ADDRESS_RESULT: '/analyze-address-result',
  ANALYZE_SMART_CONTRACT_RESULT: '/analyze-smart-contract-result',
  ANALYZE_SMART_CONTRACT_PROGRESS: '/analyze-smart-contract-progress',
  HISTORY: '/history',
  SCAN_HISTORY: '/scan-history',
  DETAIL_HISTORY: '/history/:id',
  TX_DETAIL: '/tx/:id',
  ACCOUNT: '/account',
  ANALYZE_PROGRESS: '/analyze-progress',
  FAILED: '/failed',
  WELCOME: '/welcome',
  AI_ANALYZER: '/ai-analyzer',
  SETTING: '/setting',
  ALL_NETWORK: '/all-network',
  WALLET_CONFIRMATION: '/wallet-confirmation',
  WALLET_HOME: '/wallet-home',
  MANAGE_NETWORK: '/manage-network',
  RECEIVE: '/receive',
  SEND: '/send',
  CONFIRMATION_BALANCE: '/confirmation-balance',
  RECEIVE_DETAIL: '/receive-detail',
  }