/**
 * Token Configuration
 * Contains all token-related configurations and constants
 */

// --- Mainnet tokens ---
export const TOKENS_CONFIG = [
  {
    id: 1,
    name: "Bitcoin Testnet4",
    symbol: "BTC",
    chain: "Bitcoin",
    decimals: 8,
    imageUrl: "assets/images/coins/bitcoin.webp",
    mainnet: false,
    // Token type
    type: "native",
  },
  {
    id: 2,
    name: "Sepolia Ethereum",
    symbol: "ETH",
    chain: "Ethereum",
    decimals: 18,
    imageUrl: "assets/images/coins/ethereum.webp",
    mainnet: false,
    // Token type
    type: "native",
  },
  {
    id: 3,
    name: "Solana Devnet",
    symbol: "SOL",
    chain: "Solana",
    decimals: 9,
    imageUrl: "assets/images/coins/solana.webp",
    mainnet: false,
    // Token type
    type: "native",
  },
  {
    id: 4,
    name: "Internet Computer",
    symbol: "ICP",
    chain: "Internet Computer",
    decimals: null,
    imageUrl: "assets/images/coins/icp.webp",
    mainnet: true,
    // Token type
    type: "icrc",
    canisterId: "ryjl3-tyaaa-aaaaa-aaaba-cai",
  },
  {
    id: 5,
    name: "Fradium",
    symbol: "FRADIUM",
    chain: "Internet Computer",
    decimals: null,
    imageUrl: "assets/images/coins/fradium.webp",
    mainnet: false,
    // Token type
    type: "icrc",
    canisterId: "sr4wk-4qaaa-aaaae-qfdta-cai",
  },
  {
    id: 6,
    name: "ckBTC Testnet4",
    symbol: "ckBTC",
    chain: "Internet Computer",
    decimals: null,
    imageUrl: "assets/images/coins/ckbtc.webp",
    mainnet: false,
    // Token type
    type: "icrc",
    canisterId: "mc6ru-gyaaa-aaaar-qaaaq-cai",
  },
  {
    id: 7,
    name: "ckETH Sepolia",
    symbol: "ckETH",
    chain: "Internet Computer",
    decimals: null,
    imageUrl: "assets/images/coins/cketh.webp",
    mainnet: false,
    // Token type
    type: "icrc",
    canisterId: "ss2fx-dyaaa-aaaar-qacoq-cai",
  },
  // SNS Tokens (from token.sns.json)
  {
    id: 8,
    name: "Draggin Karma Points",
    symbol: "DKP",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/zfcdd-tqaaa-aaaaq-aaaga-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "zfcdd-tqaaa-aaaaq-aaaga-cai",
    indexCanisterId: "zlaol-iaaaa-aaaaq-aaaha-cai",
    rootCanisterId: "zxeu2-7aaaa-aaaaq-aaafa-cai",
    fee: "100000",
    alternativeName: "Dragginz",
    url: "https://dragginz.io/",
  },
  {
    id: 9,
    name: "CHAT",
    symbol: "CHAT",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/2ouva-viaaa-aaaaq-aaamq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "2ouva-viaaa-aaaaq-aaamq-cai",
    indexCanisterId: "2awyi-oyaaa-aaaaq-aaanq-cai",
    rootCanisterId: "3e3x2-xyaaa-aaaaq-aaalq-cai",
    fee: "100000",
    alternativeName: "OpenChat",
    url: "https://oc.app",
  },
  {
    id: 10,
    name: "KINIC",
    symbol: "KINIC",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/73mez-iiaaa-aaaaq-aaasq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "73mez-iiaaa-aaaaq-aaasq-cai",
    indexCanisterId: "7vojr-tyaaa-aaaaq-aaatq-cai",
    rootCanisterId: "7jkta-eyaaa-aaaaq-aaarq-cai",
    fee: "100000",
    alternativeName: "Kinic",
    url: "https://kinic.io/",
  },
  {
    id: 11,
    name: "DOLR AI",
    symbol: "DOLR",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/6rdgd-kyaaa-aaaaq-aaavq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "6rdgd-kyaaa-aaaaq-aaavq-cai",
    indexCanisterId: "6dfr2-giaaa-aaaaq-aaawq-cai",
    rootCanisterId: "67bll-riaaa-aaaaq-aaauq-cai",
    fee: "100000",
    alternativeName: "DOLR AI",
    url: "https://dolr.ai",
  },
  {
    id: 12,
    name: "Mimic Clay",
    symbol: "CLAY",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/4c4fd-caaaa-aaaaq-aaa3a-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "4c4fd-caaaa-aaaaq-aaa3a-cai",
    indexCanisterId: "5ithz-aqaaa-aaaaq-aaa4a-cai",
    rootCanisterId: "4m6il-zqaaa-aaaaq-aaa2a-cai",
    fee: "100000000",
    alternativeName: "Mimic",
    url: "https://github.com/dragginzgame/mimic",
  },
  {
    id: 13,
    name: "DecideAI",
    symbol: "DCD",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/xsi2v-cyaaa-aaaaq-aabfq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "xsi2v-cyaaa-aaaaq-aabfq-cai",
    indexCanisterId: "xaonm-oiaaa-aaaaq-aabgq-cai",
    rootCanisterId: "x4kx5-ziaaa-aaaaq-aabeq-cai",
    fee: "10000",
    alternativeName: "DecideAI DAO",
    url: "https://decideai.xyz",
  },
  {
    id: 14,
    name: "BOOM",
    symbol: "BOOM",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/vtrom-gqaaa-aaaaq-aabia-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "vtrom-gqaaa-aaaaq-aabia-cai",
    indexCanisterId: "v5tde-5aaaa-aaaaq-aabja-cai",
    rootCanisterId: "xjngq-yaaaa-aaaaq-aabha-cai",
    fee: "1000000",
    alternativeName: "BOOM DAO",
    url: "https://boomdao.xyz/",
  },
  {
    id: 15,
    name: "CatalyzeDAO",
    symbol: "CTZ",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/uf2wh-taaaa-aaaaq-aabna-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "uf2wh-taaaa-aaaaq-aabna-cai",
    indexCanisterId: "ux4b6-7qaaa-aaaaq-aaboa-cai",
    rootCanisterId: "uly3p-iqaaa-aaaaq-aabma-cai",
    fee: "100000",
    alternativeName: "Catalyze",
    url: "https://catalyze.one",
  },
  {
    id: 16,
    name: "Nuance",
    symbol: "NUA",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/rxdbk-dyaaa-aaaaq-aabtq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "rxdbk-dyaaa-aaaaq-aabtq-cai",
    indexCanisterId: "q5mdq-biaaa-aaaaq-aabuq-cai",
    rootCanisterId: "rzbmc-yiaaa-aaaaq-aabsq-cai",
    fee: "100000",
    alternativeName: "Nuance",
    url: "https://nuance.xyz",
  },
  {
    id: 17,
    name: "Sonic",
    symbol: "SONIC",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/qbizb-wiaaa-aaaaq-aabwq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "qbizb-wiaaa-aaaaq-aabwq-cai",
    indexCanisterId: "qpkuj-nyaaa-aaaaq-aabxq-cai",
    rootCanisterId: "qtooy-2yaaa-aaaaq-aabvq-cai",
    fee: "100000",
    alternativeName: "SONIC",
    url: "https://app.sonic.ooo",
  },
  {
    id: 18,
    name: "GOLDAO",
    symbol: "GOLDAO",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/tyyy3-4aaaa-aaaaq-aab7a-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "tyyy3-4aaaa-aaaaq-aab7a-cai",
    indexCanisterId: "efv5g-kqaaa-aaaaq-aacaa-cai",
    rootCanisterId: "tw2vt-hqaaa-aaaaq-aab6a-cai",
    fee: "100000",
    alternativeName: "Gold DAO",
    url: "https://www.gold-dao.org",
  },
  {
    id: 19,
    name: "TRAX",
    symbol: "TRAX",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/emww2-4yaaa-aaaaq-aacbq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "emww2-4yaaa-aaaaq-aacbq-cai",
    indexCanisterId: "e6qbd-qiaaa-aaaaq-aaccq-cai",
    rootCanisterId: "ecu3s-hiaaa-aaaaq-aacaq-cai",
    fee: "100000",
    alternativeName: "TRAX",
    url: "https://trax.so",
  },
  {
    id: 20,
    name: "Neutrinite",
    symbol: "NTN",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/f54if-eqaaa-aaaaq-aacea-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "f54if-eqaaa-aaaaq-aacea-cai",
    indexCanisterId: "ft6fn-7aaaa-aaaaq-aacfa-cai",
    rootCanisterId: "extk7-gaaaa-aaaaq-aacda-cai",
    fee: "10000",
    alternativeName: "Neutrinite",
    url: "https://icpcoins.com",
  },
  {
    id: 21,
    name: "Sneed DAO",
    symbol: "SNEED",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/hvgxa-wqaaa-aaaaq-aacia-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "hvgxa-wqaaa-aaaaq-aacia-cai",
    indexCanisterId: "h3e2i-naaaa-aaaaq-aacja-cai",
    rootCanisterId: "fp274-iaaaa-aaaaq-aacha-cai",
    fee: "1000",
    alternativeName: "Sneed",
    url: "https://4pk43-5qaaa-aaaag-qc44a-cai.icp0.io/",
  },
  {
    id: 22,
    name: "ICLighthouse DAO",
    symbol: "ICL",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/hhaaz-2aaaa-aaaaq-aacla-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "hhaaz-2aaaa-aaaaq-aacla-cai",
    indexCanisterId: "gnpcd-yqaaa-aaaaq-aacma-cai",
    rootCanisterId: "hjcnr-bqaaa-aaaaq-aacka-cai",
    fee: "1000000",
    alternativeName: "ICLighthouse DAO",
    url: "https://iclight.io",
  },
  {
    id: 23,
    name: "ELNA",
    symbol: "ELNA",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/gemj7-oyaaa-aaaaq-aacnq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "gemj7-oyaaa-aaaaq-aacnq-cai",
    indexCanisterId: "gwk6g-ciaaa-aaaaq-aacoq-cai",
    rootCanisterId: "gkoex-viaaa-aaaaq-aacmq-cai",
    fee: "100000",
    alternativeName: "ELNA AI",
    url: "https://dapp.elna.ai",
  },
  {
    id: 24,
    name: "ICFC",
    symbol: "ICFC",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/ddsp7-7iaaa-aaaaq-aacqq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "ddsp7-7iaaa-aaaaq-aacqq-cai",
    indexCanisterId: "dnqcx-eyaaa-aaaaq-aacrq-cai",
    rootCanisterId: "gyito-zyaaa-aaaaq-aacpq-cai",
    fee: "100000",
    alternativeName: "ICFC",
    url: "https://icfc.app/",
  },
  {
    id: 25,
    name: "ICPanda",
    symbol: "PANDA",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/druyg-tyaaa-aaaaq-aactq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "druyg-tyaaa-aaaaq-aactq-cai",
    indexCanisterId: "c3324-riaaa-aaaaq-aacuq-cai",
    rootCanisterId: "d7wvo-iiaaa-aaaaq-aacsq-cai",
    fee: "10000",
    alternativeName: "ICPanda",
    url: "https://panda.fans",
  },
  {
    id: 26,
    name: "ICPSwap Token",
    symbol: "ICS",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/ca6gz-lqaaa-aaaaq-aacwa-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "ca6gz-lqaaa-aaaaq-aacwa-cai",
    indexCanisterId: "co4lr-qaaaa-aaaaq-aacxa-cai",
    rootCanisterId: "csyra-haaaa-aaaaq-aacva-cai",
    fee: "1000000",
    alternativeName: "ICPSwap",
    url: "https://www.icpswap.com",
  },
  {
    id: 27,
    name: "Yuku AI",
    symbol: "YUKU",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/atbfz-diaaa-aaaaq-aacyq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "atbfz-diaaa-aaaaq-aacyq-cai",
    indexCanisterId: "a5dir-yyaaa-aaaaq-aaczq-cai",
    rootCanisterId: "cj5nf-5yaaa-aaaaq-aacxq-cai",
    fee: "1000000",
    alternativeName: "Yuku AI",
    url: "https://yuku.app/",
  },
  {
    id: 28,
    name: "ESTATE",
    symbol: "EST",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/bliq2-niaaa-aaaaq-aac4q-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "bliq2-niaaa-aaaaq-aac4q-cai",
    indexCanisterId: "bfk5s-wyaaa-aaaaq-aac5q-cai",
    rootCanisterId: "abhsa-pyaaa-aaaaq-aac3q-cai",
    fee: "100000",
    alternativeName: "EstateDAO",
    url: "https://estatedao.org/",
  },
  {
    id: 29,
    name: "Motoko",
    symbol: "MOTOKO",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/k45jy-aiaaa-aaaaq-aadcq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "k45jy-aiaaa-aaaaq-aadcq-cai",
    indexCanisterId: "ks7eq-3yaaa-aaaaq-aaddq-cai",
    rootCanisterId: "ko36b-myaaa-aaaaq-aadbq-cai",
    fee: "1000000",
    alternativeName: "Motoko",
    url: "https://2uktw-yiaaa-aaaah-adwxq-cai.icp0.io/",
  },
  {
    id: 30,
    name: "Swampies",
    symbol: "SWAMP",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/lrtnw-paaaa-aaaaq-aadfa-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "lrtnw-paaaa-aaaaq-aadfa-cai",
    indexCanisterId: "ldv2p-dqaaa-aaaaq-aadga-cai",
    rootCanisterId: "l7ra6-uqaaa-aaaaq-aadea-cai",
    fee: "10000",
    alternativeName: "Swampies",
    url: "https://dragginz.io",
  },
  {
    id: 31,
    name: "ORIGYN",
    symbol: "OGY",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/lkwrt-vyaaa-aaaaq-aadhq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "lkwrt-vyaaa-aaaaq-aadhq-cai",
    indexCanisterId: "jqkzp-liaaa-aaaaq-aadiq-cai",
    rootCanisterId: "leu43-oiaaa-aaaaq-aadgq-cai",
    fee: "200000",
    alternativeName: "ORIGYN",
    url: "https://www.origyn.com/",
  },
  {
    id: 32,
    name: "WaterNeuron",
    symbol: "WTN",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/jcmow-hyaaa-aaaaq-aadlq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "jcmow-hyaaa-aaaaq-aadlq-cai",
    indexCanisterId: "iidmm-fiaaa-aaaaq-aadmq-cai",
    rootCanisterId: "jmod6-4iaaa-aaaaq-aadkq-cai",
    fee: "1000000",
    alternativeName: "WaterNeuron",
    url: "https://waterneuron.fi/",
  },
  {
    id: 33,
    name: "Poked",
    symbol: "POKED",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/np5km-uyaaa-aaaaq-aadrq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "np5km-uyaaa-aaaaq-aadrq-cai",
    indexCanisterId: "n535v-yiaaa-aaaaq-aadsq-cai",
    rootCanisterId: "nb7he-piaaa-aaaaq-aadqq-cai",
    fee: "100000000",
    alternativeName: "PokedBots",
    url: "https://www.pokedbots.com",
  },
  {
    id: 34,
    name: "ICVC",
    symbol: "ICVC",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/m6xut-mqaaa-aaaaq-aadua-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "m6xut-mqaaa-aaaaq-aadua-cai",
    indexCanisterId: "mqvz3-xaaaa-aaaaq-aadva-cai",
    rootCanisterId: "nuywj-oaaaa-aaaaq-aadta-cai",
    fee: "10000",
    alternativeName: "ICVC",
    url: "https://mnc6b-aaaaa-aaaap-qhnrq-cai.icp0.io/",
  },
  {
    id: 35,
    name: "KongSwap",
    symbol: "KONG",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/o7oak-iyaaa-aaaaq-aadzq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "o7oak-iyaaa-aaaaq-aadzq-cai",
    indexCanisterId: "onixt-eiaaa-aaaaq-aad2q-cai",
    rootCanisterId: "ormnc-tiaaa-aaaaq-aadyq-cai",
    fee: "10000",
    alternativeName: "KongSwap",
    url: "https://www.kongswap.io/",
  },
  {
    id: 36,
    name: "FomoWell",
    symbol: "WELL",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/o4zzi-qaaaa-aaaaq-aaeeq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "o4zzi-qaaaa-aaaaq-aaeeq-cai",
    indexCanisterId: "os3ua-lqaaa-aaaaq-aaefq-cai",
    rootCanisterId: "pww3s-sqaaa-aaaaq-aaedq-cai",
    fee: "100000",
    alternativeName: "FomoWell",
    url: "https://fomowell.com/",
  },
  {
    id: 37,
    name: "ALICE",
    symbol: "ALICE",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/oj6if-riaaa-aaaaq-aaeha-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "oj6if-riaaa-aaaaq-aaeha-cai",
    indexCanisterId: "mtcaz-pyaaa-aaaaq-aaeia-cai",
    rootCanisterId: "oh4fn-kyaaa-aaaaq-aaega-cai",
    fee: "500000000",
    alternativeName: "Alice",
    url: "https://alice.fun/",
  },
  {
    id: 38,
    name: "NFID Wallet",
    symbol: "NFIDW",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/mih44-vaaaa-aaaaq-aaekq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "mih44-vaaaa-aaaaq-aaekq-cai",
    indexCanisterId: "mgfru-oqaaa-aaaaq-aaelq-cai",
    rootCanisterId: "m2blf-zqaaa-aaaaq-aaejq-cai",
    fee: "10000",
    alternativeName: "NFID Wallet",
    url: "https://nfid.one/",
  },
  {
    id: 39,
    name: "FUEL",
    symbol: "FUEL",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/nfjys-2iaaa-aaaaq-aaena-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "nfjys-2iaaa-aaaaq-aaena-cai",
    indexCanisterId: "nxppl-wyaaa-aaaaq-aaeoa-cai",
    rootCanisterId: "nllv2-byaaa-aaaaq-aaema-cai",
    fee: "100000",
    alternativeName: "FuelEV",
    url: "https://fuelev.ai/",
  },
  {
    id: 40,
    name: "ICExplorer",
    symbol: "ICE",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/ifwyg-gaaaa-aaaaq-aaeqq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "ifwyg-gaaaa-aaaaq-aaeqq-cai",
    indexCanisterId: "iluvo-5qaaa-aaaaq-aaerq-cai",
    rootCanisterId: "n6mex-aqaaa-aaaaq-aaepq-cai",
    fee: "100000",
    alternativeName: "IC Explorer",
    url: "https://icexplorer.io",
  },
  {
    id: 41,
    name: "Personal DAO",
    symbol: "DAO",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/ixqp7-kqaaa-aaaaq-aaetq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "ixqp7-kqaaa-aaaaq-aaetq-cai",
    indexCanisterId: "j57nf-iaaaa-aaaaq-aaeuq-cai",
    rootCanisterId: "izscx-raaaa-aaaaq-aaesq-cai",
    fee: "10000",
    alternativeName: "Personal DAO",
    url: "https://gsnnn-ziaaa-aaaag-acaaa-cai.icp0.io/",
  },
  {
    id: 42,
    name: "Cecil The Lion DAO",
    symbol: "CECIL",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/jg2ra-syaaa-aaaaq-aaewa-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "jg2ra-syaaa-aaaaq-aaewa-cai",
    indexCanisterId: "jiy4i-jiaaa-aaaaq-aaexa-cai",
    rootCanisterId: "ju4gz-6iaaa-aaaaq-aaeva-cai",
    fee: "1000000",
    alternativeName: "Cecil The Lion DAO",
    url: "https://cecildao.org",
  },
  {
    id: 43,
    name: "ICPEx",
    symbol: "ICX",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/lvfsa-2aaaa-aaaaq-aaeyq-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "lvfsa-2aaaa-aaaaq-aaeyq-cai",
    indexCanisterId: "l3h7i-bqaaa-aaaaq-aaezq-cai",
    rootCanisterId: "jpz24-eqaaa-aaaaq-aaexq-cai",
    fee: "100000",
    alternativeName: "ICPEx",
    url: "https://icpex.org/",
  },
  {
    id: 44,
    name: "TACO DAO Token",
    symbol: "TACO",
    chain: "Internet Computer",
    decimals: 8,
    imageUrl: "assets/images/coins/sns/kknbx-zyaaa-aaaaq-aae4a-cai.png",
    mainnet: true,
    type: "sns",
    ledgerCanisterId: "kknbx-zyaaa-aaaaq-aae4a-cai",
    indexCanisterId: "kepm7-ciaaa-aaaaq-aae5a-cai",
    rootCanisterId: "lacdn-3iaaa-aaaaq-aae3a-cai",
    fee: "10000",
    alternativeName: "TACO DAO",
    url: "https://tacodao.com",
  },
];

// API Keys for different services
export const API_KEYS = {
  ETHERSCAN_API_KEY: process.env.VITE_ETHERSCAN_API_KEY,
  COINGECKO_API_KEY: process.env.VITE_COINGGECKO_API_KEY,
  COINMARKETCAP_API_KEY: process.env.VITE_COINMARKETCAP_API_KEY,
};

// Validate required API keys
if (!API_KEYS.ETHERSCAN_API_KEY) {
  throw new Error("VITE_ETHERSCAN_API_KEY environment variable is required but not set");
}

// CoinGecko API key is optional but recommended for higher rate limits
// Get your free API key at: https://www.coingecko.com/en/api
// Add it to your .env file as: VITE_COINGECKO_API_KEY=your_api_key_here
if (!API_KEYS.COINGECKO_API_KEY) {
  console.warn("VITE_COINGECKO_API_KEY not set. Using free tier with rate limits (10-50 calls/minute).");
  console.warn("Get your free API key at: https://www.coingecko.com/en/api");
}

// CoinMarketCap API key is optional but recommended for better rate limits
// Get your free API key at: https://coinmarketcap.com/api/
// Add it to your .env file as: VITE_COINMARKETCAP_API_KEY=your_api_key_here
if (!API_KEYS.COINMARKETCAP_API_KEY) {
  console.warn("VITE_COINMARKETCAP_API_KEY not set. Using free tier with rate limits (10,000 calls/month).");
  console.warn("Get your free API key at: https://coinmarketcap.com/api/");
}

export const API_URLS = {
  ethereum: {
    sepolia: `https://api-sepolia.etherscan.io/api?module=account&action=txlist&apikey=${API_KEYS.ETHERSCAN_API_KEY}`,
    mainnet: `https://api.etherscan.io/api?module=account&action=txlist&apikey=${API_KEYS.ETHERSCAN_API_KEY}`,
  },
  bitcoin: {
    testnet: "https://api.blockcypher.com/v1/btc/test3",
    mainnet: "https://api.blockcypher.com/v1/btc/main",
  },
  solana: {
    devnet: "https://api.devnet.solana.com",
    mainnet: "https://api.mainnet-beta.solana.com",
  },
};

// Network configuration for WalletLayout compatibility
export const NETWORK_CONFIG = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    icon: "/assets/images/networks/bitcoin.webp",
  },
  {
    id: "ethereum",
    name: "Ethereum",
    icon: "/assets/images/networks/ethereum.webp",
  },
  {
    id: "solana",
    name: "Solana",
    icon: "/assets/images/networks/solana.webp",
  },
  {
    id: "icp",
    name: "Internet Computer",
    icon: "/assets/images/networks/icp.webp",
  },
];

// Map token symbols to CoinGecko IDs
export const COINGECKO_IDS = {
  BTC: "bitcoin",
  ETH: "ethereum",
  SOL: "solana",
  ICP: "internet-computer",
  FADM: "fradium", // Note: Fradium might not be on CoinGecko, we'll handle this
  ckBTC: "bitcoin", // ckBTC uses BTC price
  ckETH: "ethereum", // ckETH uses ETH price
  // SNS Tokens - most won't be on CoinGecko, will use fallback prices
  DKP: "draggin-karma-points",
  CHAT: "openchat",
  KINIC: "kinic",
  DOLR: "dolr-ai",
  CLAY: "mimic-clay",
  DCD: "decideai",
  BOOM: "boom-dao",
  CTZ: "catalyze",
  NUA: "nuance",
  SONIC: "sonic",
  GOLDAO: "gold-dao",
  TRAX: "trax",
  NTN: "neutrinite",
  SNEED: "sneed-dao",
  ICL: "iclighthouse-dao",
  ELNA: "elna-ai",
  ICFC: "icfc",
  PANDA: "icpanda",
  ICS: "icpswap",
  YUKU: "yuku-ai",
  EST: "estate",
  MOTOKO: "motoko",
  SWAMP: "swampies",
  OGY: "origyn",
  WTN: "waterneuron",
  POKED: "poked",
  ICVC: "icvc",
  KONG: "kongswap",
  WELL: "fomowell",
  ALICE: "alice",
  NFIDW: "nfid-wallet",
  FUEL: "fuel",
  ICE: "icexplorer",
  DAO: "personal-dao",
  CECIL: "cecil-dao",
  ICX: "icpex",
  TACO: "taco-dao",
};

// CoinMarketCap IDs
export const COINMARKETCAP_IDS = {
  BTC: "1",
  ETH: "1027",
  SOL: "5426",
  ICP: "8916",
  ckBTC: "1", // ckBTC uses BTC price
  ckETH: "1027", // ckETH uses ETH price
};

// CoinPaprika IDs
export const COINPAPRIKA_IDS = {
  BTC: "btc-bitcoin",
  ETH: "eth-ethereum",
  SOL: "sol-solana",
  ICP: "icp-internet-computer",
  ckBTC: "btc-bitcoin", // ckBTC uses BTC price
  ckETH: "eth-ethereum", // ckETH uses ETH price
};

// Fallback prices for tokens not supported by major APIs
export const FALLBACK_PRICES = {
  BTC: 0,
  ETH: 0,
  SOL: 0,
  ICP: 0,
  FADM: 0, // Placeholder price for Fradium
  ckBTC: 0, // ckBTC uses BTC price, fallback to 0
  ckETH: 0, // ckETH uses ETH price, fallback to 0
  // SNS Tokens - fallback prices (most will be 0 until they get listed)
  DKP: 0,
  CHAT: 0,
  KINIC: 0,
  DOLR: 0,
  CLAY: 0,
  DCD: 0,
  BOOM: 0,
  CTZ: 0,
  NUA: 0,
  SONIC: 0,
  GOLDAO: 0,
  TRAX: 0,
  NTN: 0,
  SNEED: 0,
  ICL: 0,
  ELNA: 0,
  ICFC: 0,
  PANDA: 0,
  ICS: 0,
  YUKU: 0,
  EST: 0,
  MOTOKO: 0,
  SWAMP: 0,
  OGY: 0,
  WTN: 0,
  POKED: 0,
  ICVC: 0,
  KONG: 0,
  WELL: 0,
  ALICE: 0,
  NFIDW: 0,
  FUEL: 0,
  ICE: 0,
  DAO: 0,
  CECIL: 0,
  ICX: 0,
  TACO: 0,
};

// Token type mappings
export const TOKEN_TYPE_MAPPINGS = {
  Bitcoin: "Bitcoin",
  Ethereum: "Ethereum",
  Solana: "Solana",
  "Internet Computer": "Internet Computer",
};

// Default decimals for tokens
export const DEFAULT_DECIMALS = {
  BTC: 8,
  ETH: 18,
  SOL: 9,
  ICP: 8,
  FRADIUM: 8,
  ckBTC: 8,
  ckETH: 18,
  // SNS Tokens - all have 8 decimals
  DKP: 8,
  CHAT: 8,
  KINIC: 8,
  DOLR: 8,
  CLAY: 8,
  DCD: 8,
  BOOM: 8,
  CTZ: 8,
  NUA: 8,
  SONIC: 8,
  GOLDAO: 8,
  TRAX: 8,
  NTN: 8,
  SNEED: 8,
  ICL: 8,
  ELNA: 8,
  ICFC: 8,
  PANDA: 8,
  ICS: 8,
  YUKU: 8,
  EST: 8,
  MOTOKO: 8,
  SWAMP: 8,
  OGY: 8,
  WTN: 8,
  POKED: 8,
  ICVC: 8,
  KONG: 8,
  WELL: 8,
  ALICE: 8,
  NFIDW: 8,
  FUEL: 8,
  ICE: 8,
  DAO: 8,
  CECIL: 8,
  ICX: 8,
  TACO: 8,
};

// Cache configuration
export const CACHE_CONFIG = {
  BALANCE_CACHE_DURATION: 5 * 60 * 1000, // 5 minutes in milliseconds
  BALANCE_CACHE_PREFIX: "balanceCache_",
};
